name: "Build Image"

on:
  push:
    branches:
      - master
    tags-ignore:
      - "release*"

jobs:
  build_image_job:
    runs-on: ubuntu-latest
    name: Publish Docker image
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u gtoru --password-stdin
      - name: Build Historical Image
        run: docker build -t docker.pkg.github.com/gtoru/front/front:$GITHUB_RUN_NUMBER --target deploy --build-arg npm_token=${{ secrets.GITHUB_TOKEN }} .
      - name: Publish Historical Image
        run: docker push docker.pkg.github.com/gtoru/front/front:$GITHUB_RUN_NUMBER
      - name: Build Latest Image
        run: docker build -t docker.pkg.github.com/gtoru/front/front --target deploy --build-arg npm_token=${{ secrets.GITHUB_TOKEN }} .
      - name: Publish Latest Image
        run: docker push docker.pkg.github.com/gtoru/front/front

  update_job:
    runs-on: ubuntu-latest
    name: Perform DEV cluster update
    needs: build_image_job
    steps:
      - uses: actions/checkout@v2
      - name: Configure k8s
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: 'mkdir ~/.kube && echo "$KUBECONFIG" > ~/.kube/config'
      - name: Set gto-dev namespace for kubectl
        run: kubectl config set-context --current --namespace=gto-dev
      - name: Add Github-token as secret
        run: kubectl get secrets regcred || kubectl create secret docker-registry regcred --namespace=gto-dev --docker-server=docker.pkg.github.com --docker-username=gtoru --docker-password=${{ secrets.GITHUB_TOKEN }}
      - name: Rollout update
        run: kubectl rollout restart deployment/gto-front-deployment
